### ISSUE TITLE
I am getting a Not yet implemented error.

### ISSUE THREAD

**Issue by SEISENREICH1** [bbaia/protractor-net#49]
I get this error when I am trying to send text to an element on a mobile app built using ionic:

System.NotImplementedException was unhandled by user code
  HResult=-2147467263
  Message=Not yet implemented. Please help us: http://appium.io/get-involved.html
  Source=WebDriver
  StackTrace:
       at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
       at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
       at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteAsyncScript(String script, Object[] args)
       at Protractor.NgWebDriver.WaitForAngular() in c:\Users\Bruno\Projets\GitHub\bbaia\protractor-net\src\Protractor\NgWebDriver.cs:line 364
       at Protractor.NgWebDriver.FindElement(By by) in c:\Users\Bruno\Projets\GitHub\bbaia\protractor-net\src\Protractor\NgWebDriver.cs:line 279
       at Protractor.NgWebDriver.OpenQA.Selenium.ISearchContext.FindElement(By by) in c:\Users\Bruno\Projets\GitHub\bbaia\protractor-net\src\Protractor\NgWebDriver.cs:line 304
       at OpenQA.Selenium.Support.UI.ExpectedConditions.<>c__DisplayClass10.<ElementExists>b__f(IWebDriver driver)

**Comment by bbaia** [comment]
Looks like an NotImplementedException from the Appium Framework (http://appium.io)
