### ISSUE TITLE
Edge Browser Support

### ISSUE THREAD

**Issue by amitraturi** [bbaia/protractor-net#58]
Hi,

Are we supporting the edge browser. I am using below packages  and getting error on running test with protractor :+1: 
  _<package id="Protractor" version="0.9.1" targetFramework="net46" />
  <package id="Selenium.Support" version="2.53.1" targetFramework="net46" />
  <package id="Selenium.WebDriver" version="3.0.0" targetFramework="net46" />
  <package id="Selenium.WebDriver.ChromeDriver" version="2.25.0.0" targetFramework="net46" />
  <package id="Selenium.WebDriver.MicrosoftWebDriver" version="10.0.10240.0" targetFramework="net46" />
<package id="WebDriver.IEDriverServer.win32" version="2.53" targetFramework="net46" />_

**Code:**
private static IWebDriver driver;
private static NgWebDriver ngDriver;

driver = new EdgeDriver();
                     driver.Navigate().GoToUrl(ConfigurationManager.AppSettings.Get("ServerHost") + TestVariable.loginPath);
Thread.Sleep(1000);
driver.FindElement(By.Name("username")).Clear();
driver.FindElement(By.Name("username")).SendKeys("tenant1");

**//With above step the action was performed but with below operation is not successful**
ngDriver = new NgWebDriver(driver);
ngDriver.FindElement(By.Name("username")).Clear();
ngDriver.FindElement(By.Name("username")).SendKeys("tenant1");

**Error:**
Waiting for new request...

   WebUI.Test.Entity.Feature.EntityFeature.ConfirmationMessageIsDisplayedAfterCreatingEntity_ [FAIL]
      System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
      ---- System.NotImplementedException : not implemented
      Stack Trace:
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
            at BoDi.ObjectContainer.CreateObject(Type type, IEnumerable`1 resolutionPath, RegistrationKey keyToResolve)
            at BoDi.ObjectContainer.TypeRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, IEnumerable`1 resolutionPath)
            at BoDi.ObjectContainer.CreateObjectFor(RegistrationKey keyToResolve, IEnumerable`1 resolutionPath)
            at BoDi.ObjectContainer.Resolve(Type typeToResolve, IEnumerable`1 resolutionPath, String name)
            at lambda_method(Closure , IContextManager , String )
            at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
            at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
            at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
            at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
            at WebUI.Test.Entity.Feature.EntityFeature.ScenarioCleanup()
            at WebUI.Test.Entity.Feature.EntityFeature.ConfirmationMessageIsDisplayedAfterCreatingEntity_()
         ----- Inner Stack Trace -----
            at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
            at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
            at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
         c:\Users\Bruno\Projets\GitHub\bbaia\protractor-net\src\Protractor\NgWebDriver.cs(370,0): at Protractor.NgWebDriver.WaitForAngular()
         c:\Users\Bruno\Projets\GitHub\bbaia\protractor-net\src\Protractor\NgWebDriver.cs(283,0): at Protractor.NgWebDriver.FindElement(By by)
            at WebdriverBdd.TestConfiguration.get_Driver()
            at WebUI.Test.Rome.StepDefination.ModelStepDefinition..ctor(RuntimeTestData testData)
Finished:    WebUI.Test

Thanks
Amit

**Comment by bbaia** [comment]
Microsoft Edge is supported since v0.8.1

You need to keep drivers up to date because your browser is automatically updated. 
Plz update the "Selenium.WebDriver.MicrosoftWebDriver" package and try again.

**Comment by amitraturi** [comment]
Hi,

Thanks for the suggestion. Actually I used the old version because with that at least selenium test were working. When i used the latest version i am getting issue with driver. Pop up error  “The ordinal 870 could not be located in the dynamic link library C:\Users\raturia\Automation\WebUI.Test\bin\Debug\MicrosoftWebDriver.exe.” with below stack trace. The earlier version 10.0.10240.0 was working without any error.

**Updated Packages:**
"Protractor" version="0.9.1"
"Selenium.Support" version="3.0.1"
"Selenium.WebDriver" version="3.0.1"
"Selenium.WebDriver.ChromeDriver" version="2.27.0.0"
"Selenium.WebDriver.MicrosoftWebDriver" version="10.0.14393.0"
"WebDriver.IEDriverServer.win32" version="2.53"

**Error Stack:**
      System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
      ---- OpenQA.Selenium.WebDriverException : Cannot start the driver service on http://localhost:65111/
      Stack Trace:
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
            at BoDi.ObjectContainer.CreateObject(Type type, IEnumerable`1 resolutionPath, RegistrationKey keyToResolve)
            at BoDi.ObjectContainer.TypeRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, IEnumerable`1 resolutionPath)
            at BoDi.ObjectContainer.CreateObjectFor(RegistrationKey keyToResolve, IEnumerable`1 resolutionPath)
            at BoDi.ObjectContainer.Resolve(Type typeToResolve, IEnumerable`1 resolutionPath, String name)
            at lambda_method(Closure , IContextManager , String )
            at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
            at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
            at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
            at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
         C:\Perforce\APP\RO\Main\QA\Automation\UI\WebUI.Test\Entity\Feature\Entity.feature.cs(0,0): at WebUI.Test.Entity.Feature.EntityFeature.ScenarioCleanup()
         C:\Perforce\APP\RO\Main\QA\Automation\UI\WebUI.Test\Entity\Feature\Entity.feature(21,0): at WebUI.Test.Entity.Feature.EntityFeature.EntityCreatedIsVisibleInROAfterCreation()
         ----- Inner Stack Trace -----
            at OpenQA.Selenium.DriverService.Start()
            at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
            at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
            at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
            at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
            at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeOptions options)
         C:\Perforce\APP\RO\Main\QA\Automation\UI\WebUI.Test\Utilities\TestConfiguration.cs(102,0): at WebdriverBdd.TestConfiguration.get_Driver()
         C:\Perforce\APP\RO\Main\QA\Automation\UI\WebUI.Test\Rome\StepDefination\ModelStepDefinition.cs(21,0): at WebUI.Test.Rome.StepDefination.ModelStepDefinition..ctor(RuntimeTestData testData)
Finished:    WebUI.Test
