### ISSUE TITLE
Because of Selenium update Navigate works no more.

### ISSUE THREAD

**Issue by asartem** [bbaia/protractor-net#78]
Looks like its because of the update of Selenium.
Function Navigate works no more. 
Versions:
protractor: latest
Selenium 3.14.0 (web driver, support and chromedriver)
Chrome browser latest.

Error details:
Method not found: 'System.String OpenQA.Selenium.ICapabilities.get_BrowserName()'.

Stacktrace:

 at Protractor.NgWebDriver.set_Url(String value)
   at Protractor.NgNavigation.GoToUrl(String url) in c:\Users\Bruno\Projets\GitHub\bbaia\protractor-net\src\Protractor\NgNavigation.cs:line 101
   at SC.Web.Client.Tests.Framework.Models.Common.PageObject.NavigateToLocation(String pageLocalPath, Nullable`1 waitTimeoutInSeconds) in C:\Sources\SCgit\Web\Tests\SC.Web.Client.Tests\Framework\Models\Common\PageObject.cs:line 291

**Comment by sgadoury** [comment]
I have the same problem.

The driver creation code looks like this:
```
            var chromeOptions = new ChromeOptions();
            chromeOptions.AddArguments("test-type");
            chromeOptions.AddArguments("start-maximized");
            chromeOptions.AddArguments("--disable-extensions");
            chromeOptions.AddArguments("no-sandbox");
            chromeOptions.AddArguments("disable-infobars");

            Driver = new ChromeDriver(chromeOptions);
            Driver.Manage().Timeouts().AsynchronousJavaScript = TimeSpan.FromSeconds(10);

            NgDriver = new NgWebDriver(Driver);
```

When I do `Driver.Url = "http://url..."`, it works.  However, when I enter `NgDriver.Url = "http://url..."`, I got the Method not found for browsername.

@bbaia : Do you have any workaround for us?  When do you think a fix will be available?

Thank you

**Comment by SubjectiveReality** [comment]
Is @bbaia or anybody actively looking at issues, or anybody else working on a fork if not?

**Comment by bbaia** [comment]
Available with v0.12

**Comment by dessap** [comment]
I'm still having this issue on Protractor.Net.Standard version 0.12. This version is pointing to Selenium.Webdriver v 3.141.0 rather than 3.14.0. Could you please let me know if you can replicate it?
Code
var driver = new FirefoxDriver((FirefoxOptions)options);
var ngdriver = new NgWebDriver(driver);
ngdriver.IgnoreSynchronization = true;
TryMaximize(ngdriver);
ngdriver.Visit(BaseUrl);

Output
Setting target browser to: Firefox
System.MissingMethodException : Method not found: 'System.String OpenQA.Selenium.ICapabilities.get_BrowserName()'.Result message:
System.MissingMethodException : Method not found: 'System.String OpenQA.Selenium.ICapabilities.get_BrowserName()'.
